<?php
function barra_lateral_principal(){
    if ($_SESSION['nivel_usuario'] == 1) {
        echo 
        '
        <div class="banner " id="mainHeader" role="banner">
        
                <nav role="navigation" class="bg-info text-start">
                    <div class="top-header">
                        <div class="navg">
                        <div class="efect"></div>
                        </div>
                    </div>
        
                    <!-- This part is the navigation generated by Wordpress.  -->
                    <ul id="menu-vertical-menu" class="nav "  >
                        <li><a href="index_intranet.php" id="enl_barra">Inicio</a></li>
                        <li><a href="soporte_tecnico.php" id="enl_barra">Centro de Soporte</a></li>
                        <li><a href="parque_tecno.php" id="enl_barra">Parque Tecnologico</a></li>
                        <li><a href="correspondencia_menu.php" id="enl_barra">Correspondencia</a></li>
                        <li><a href="gestion_usuario.php" id="enl_barra">Gestion de Usuario</a></li>  
                        
                        <li><a href="../php/cerrar_sesion.php" id="enl_barra" class="text-light">Cerrar Sesión</a></li> 
                    </ul>
                </nav>
        
            </div>
        
        ';
    }
    else if ($_SESSION['nivel_usuario'] == 2) {
        echo 
        '
        <div class="banner " id="mainHeader" role="banner">
        
                <nav role="navigation" class="bg-info text-start">
                    <div class="top-header">
                        <div class="navg">
                        <div class="efect"></div>
                        </div>
                    </div>
        
                    <!-- This part is the navigation generated by Wordpress.  -->
                    <ul id="menu-vertical-menu" class="nav "  >
                        <li><a href="index_intranet.php" id="enl_barra">Inicio</a></li>
                        <li><a href="soporte_tecnico.php" id="enl_barra">Centro de Soporte</a></li>
                        <li><a href="parque_tecno.php" id="enl_barra">Parque Tecnologico</a></li>
                        
                        <li><a href="../php/cerrar_sesion.php" id="enl_barra" class="text-light">Cerrar Sesión</a></li> 
                    </ul>
                </nav>
        
            </div>
        
        ';
    }
    else if ($_SESSION['nivel_usuario'] == 3) {
        echo 
        '
        <div class="banner " id="mainHeader" role="banner">
        
                <nav role="navigation" class="bg-info text-start">
                    <div class="top-header">
                        <div class="navg">
                        <div class="efect"></div>
                        </div>
                    </div>
        
                    <!-- This part is the navigation generated by Wordpress.  -->
                    <ul id="menu-vertical-menu" class="nav "  >
                        <li><a href="index_intranet.php" id="enl_barra">Inicio</a></li>
                        <li><a href="soporte_tecnico.php" id="enl_barra">Centro de Soporte</a></li>
                        <li><a href="correspondencia_menu.php" id="enl_barra">Correspondencia</a></li>
                        
                        <li><a href="../php/cerrar_sesion.php" id="enl_barra" class="text-light">Cerrar Sesión</a></li> 
                    </ul>
                </nav>
        
            </div>
        
        ';
    }
    else if ($_SESSION['nivel_usuario'] == 4) {
        echo 
        '
        <div class="banner " id="mainHeader" role="banner">
        
                <nav role="navigation" class="bg-info text-start">
                    <div class="top-header">
                        <div class="navg">
                        <div class="efect"></div>
                        </div>
                    </div>
        
                    <!-- This part is the navigation generated by Wordpress.  -->
                    <ul id="menu-vertical-menu" class="nav "  >
                        <li><a href="index_intranet.php" id="enl_barra">Inicio</a></li>
                        <li><a href="soporte_tecnico.php" id="enl_barra">Centro de Soporte</a></li>
                        
                        <li><a href="../php/cerrar_sesion.php" id="enl_barra" class="text-light">Cerrar Sesión</a></li> 
                    </ul>
                </nav>
        
            </div>
        
        ';
    }
    
   
}
