<?php
// $anterior = "http://localhost/Proyecto2022-2023/intranet/index_intranet.php";
// Variable global
$anterior = "../intranet/index_intranet.php";
$url_no_deseada = "../intranet/gestion_usuario_rol.php";
$url_no_deseada2 = "../intranet/gestion_usuario_recup.php";

// Verifica si la URL de la referencia es válida
if (isset($_SERVER['HTTP_REFERER']) && filter_var($_SERVER['HTTP_REFERER'], FILTER_VALIDATE_URL)) {
    $anterior = $_SERVER['HTTP_REFERER'];

    // Verifica si la URL de la referencia es igual a la URL no deseada
    if ($anterior == $url_no_deseada || $anterior == $url_no_deseada2 ) {
        $anterior = "../intranet/index_intranet.php";
    }
  }
function barra_lateral_nue_equipo(){
    echo 
    '
    <div class="banner " id="mainHeader" role="banner">
    
            <nav role="navigation" class="bg-info text-start">
                <div class="top-header">
                    <div class="navg">
                    <div class="efect"></div>
                    </div>
                </div>
    
                <!-- This part is the navigation generated by Wordpress.  -->
                <ul id="menu-vertical-menu" class="nav"  >
                    <li>
                        <button id="ubi_resp" class="limpiador-botones" onclick="cambioPesta1();" ><img src="../assets/intranet/parque_tecnologico/iconos/ubicacion.png" class="img-btn">Ubicación y Responsable</button>
                    </li>
                    <li>
                        <button id="especificaciones" class="limpiador-botones" onclick="cambioPesta2();"><img src="../assets/intranet/parque_tecnologico/iconos/monitor.png" class="img-btn">Especifícaciones</button>
                    </li>
                    <li>
                        <button id="componentes" class="limpiador-botones" onclick="cambioPesta3();"><img src="../assets/intranet/parque_tecnologico/iconos/teclado.png" class="img-btn">Componentes</button>
                    </li>
                    <li class="mb-5">
                        <button id="componentes2" class="limpiador-botones" onclick="cambioPesta4();"><img src="../assets/intranet/parque_tecnologico/iconos/escaner.png" class="img-btn">Otros Componentes</button>
                    </li>
                    <li>
                        <button class="limpiador-botones" >    
                            <a href="parque_tecno.php" class="enlaces_limpios"><img src="../assets/icon/users/log-out.png" class="img-btn">Volver</a>
                        </button>
                        
                    </li>               
                </ul>
            </nav>
    
        </div>
    
    ';
}
function barra_lateral_consul_equipo(){
    echo 
    '
    <div class="banner " id="mainHeader" role="banner">
    
            <nav role="navigation" class="bg-info text-start">
                <div class="top-header">
                    <div class="navg">
                    <div class="efect"></div>
                    </div>
                </div>
    
                <!-- This part is the navigation generated by Wordpress.  -->
                <ul id="menu-vertical-menu" class="nav"  >
                    <li>
                        <button id="estadiscEquip" class="limpiador-botones" onclick="cambioPesta4();"><img src="../assets/intranet/grafico.png" class="img-btn">Datos</button>
                    </li>
                   
                    <li>
                        <button id="consulta_rami" class="limpiador-botones" onclick="cambioPesta1();" ><img src="../assets/intranet/parque_tecnologico/iconos/separar.png" class="img-btn">Por Dirección o Ramificaciones</button>
                    </li>
                    <li>
                        <button id="consulta_fecha" class="limpiador-botones" onclick="cambioPesta2();"><img src="../assets/intranet/parque_tecnologico/iconos/calendario.png" class="img-btn">Por Fecha</button>
                    </li>
                    <li class="mb-5">
                        <button id="componentes2" class="limpiador-botones" onclick="cambioPesta3();"><img src="../assets/intranet/parque_tecnologico/iconos/todo-en-uno.png" class="img-btn">Imprimir Todos los Equipos</button>
                    </li>
                    
                    
                    <li>
                        <button class="limpiador-botones" >
                            <a href="parque_tecno.php" class="enlaces_limpios"><img src="../assets/icon/users/log-out.png" class="img-btn">Volver</a>
                        </button>
                        
                    </li>                
                </ul>
            </nav>
    
        </div>
    
    ';
}
function barra_lateral_soporte_notifi(){
    echo 
    '
    <div class="banner " id="mainHeader" role="banner">
    
            <nav role="navigation" class="bg-info text-start">
                <div class="top-header">
                    <div class="navg">
                    <div class="efect"></div>
                    </div>
                </div>
    
                <ul id="menu-vertical-menu" class="nav"  >
                    <li>
                        <button id="cambio4" class="limpiador-botones" onclick="cambioPesta4();"><img src="../assets/intranet/grafico.png" class="img-btn">Datos<input  id="datos" class="display-inline w-15  limpiador-botones text-light text-center" disabled ></button>
                    </li>
                    <li>
                        <button id="cambio1" class="limpiador-botones" onclick="cambioPesta1();"><img src="../assets/intranet/soporte/iconos/solicitud.png" class="img-btn">Solicitudes en espera<input  id="espera" class="display-inline w-15  limpiador-botones text-light text-center" disabled ></button>
                    </li>
                    <li>
                        <button id="cambio2" class="limpiador-botones" onclick="cambioPesta2();"><img src="../assets/intranet/soporte/iconos/perfiles.png" class="img-btn">Solicitudes para finalizar<input  id="procesoN" class="display-inline w-15  limpiador-botones text-light text-center" disabled ></button>
                    </li>
                    <li>
                        <button id="cambio3" class="limpiador-botones" onclick="cambioPesta3();"><img src="../assets/intranet/soporte/iconos/rechazo.png" class="img-btn">Solicitudes rechazadas<input  id="rechazado" class="display-inline w-15  limpiador-botones text-light text-center" disabled ></button>
                    </li>
                    <li>
                        <button class="limpiador-botones" >
                            <a href="soporte_tecnico.php" class="enlaces_limpios"><img src="../assets/icon/users/log-out.png" class="img-btn">Volver</a>
                        </button>
                    </li>               
                </ul>
            </nav>
    
        </div>
    
    ';
}

function barra_lateral_ajustes_usuario(){
    echo 
    '
    <div class="banner " id="mainHeader" role="banner">
    
            <nav role="navigation" class="bg-info text-start">
                <div class="top-header">
                    <div class="navg">
                    <div class="efect"></div>
                    </div>
                </div>
    
                <!-- This part is the navigation generated by Wordpress.  -->
                <ul id="menu-vertical-menu" class="nav"  >
                    <li>
                        <button id="cambio1" class="limpiador-botones" onclick="cambioPesta1();" ><img src="../assets/icon/users/usuario-de-perfil.png" class="img-btn">Modificar Usuario</button>
                    </li>
                    <li>
                        <button id="cambio2" class="limpiador-botones" onclick="cambioPesta2();"><img src="../assets/icon/users/preguntas-mas-frecuentes.png" class="img-btn">Modificar Preguntas de Seguridad</button>
                    </li>
                    <li>
                        <button class="limpiador-botones" >
                            <a href="index_intranet.php" class="enlaces_limpios"><img src="../assets/icon/users/log-out.png" class="img-btn">Volver</a>
                        </button>
                    </li>               
                </ul>
            </nav>
    
        </div>
    
    ';
}

function barra_lateral_recuperacion(){
    echo 
    '
    <div class="banner " id="mainHeader" role="banner">
    
            <nav role="navigation" class="bg-info text-start">
                <div class="top-header">
                    <div class="navg">
                    <div class="efect"></div>
                    </div>
                </div>
    
                <!-- This part is the navigation generated by Wordpress.  -->
                <ul id="menu-vertical-menu" class="nav"  >
                    <li>
                        <button id="cambio1" class="limpiador-botones" onclick="cambioPesta1();" ><img src="../assets/icon/users/usuario-de-perfil.png" class="img-btn">Recuperación</button>
                    </li>

                    <li>
                        <button class="limpiador-botones" >
                            <a href="../intranet/gestion_usuario.php" class="enlaces_limpios"><img src="../assets/icon/users/log-out.png" class="img-btn">Volver</a>
                        </button>
                    </li>               
                </ul>
            </nav>
    
        </div>
    
    ';
}
function barra_lateral_individual($TitlePag){
    global $anterior;
    echo 
    '
    <div class="banner " id="mainHeader" role="banner">
    
            <nav role="navigation" class="bg-info text-start">
                <div class="top-header">
                    <div class="navg">
                    <div class="efect"></div>
                    </div>
                </div>
    
                <!-- This part is the navigation generated by Wordpress.  -->
                <ul id="menu-vertical-menu" class="nav"  >
                    <li>
                        <button id="cambio1" class="limpiador-botones" onclick="cambioPesta1();" ><img src="../assets/icon/users/usuario-de-perfil.png" class="img-btn">'.$TitlePag.'</button>
                    </li>

                    <li>
                        <button class="limpiador-botones" >
                            <a href="'.$anterior.'" class="enlaces_limpios"><img src="../assets/icon/users/log-out.png" class="img-btn">Volver</a>
                        </button>
                    </li>               
                </ul>
            </nav>
    
        </div>
    
    ';
}
function barra_lateral_recuperacion_usuario(){
    echo 
    '
    <div class="banner " id="mainHeader" role="banner">
    
            <nav role="navigation" class="bg-info text-start">
                <div class="top-header">
                    <div class="navg">
                    <div class="efect"></div>
                    </div>
                </div>
    
                <!-- This part is the navigation generated by Wordpress.  -->
                <ul id="menu-vertical-menu" class="nav"  >
                    <li>
                        <button id="cambio1" class="limpiador-botones" onclick="cambioPesta1();" ><img src="../assets/icon/users/usuario-de-perfil.png" class="img-btn">Recuperación</button>
                    </li>

                    <li>
                        <button class="limpiador-botones" >
                            <a href="../intranet/gestion_usuario.php" class="enlaces_limpios"><img src="../assets/icon/users/log-out.png" class="img-btn">Volver</a>
                        </button>
                    </li>               
                </ul>
            </nav>
    
        </div>
    
    ';
}
function barra_lateral_cambioRol(){
    echo 
    '
    <div class="banner " id="mainHeader" role="banner">
    
            <nav role="navigation" class="bg-info text-start">
                <div class="top-header">
                    <div class="navg">
                    <div class="efect"></div>
                    </div>
                </div>
    
                <!-- This part is the navigation generated by Wordpress.  -->
                <ul id="menu-vertical-menu" class="nav"  >
                    <li>
                        <button id="cambio1" class="limpiador-botones" onclick="cambioPesta1();" ><img src="../assets/icon/users/usuario-de-perfil.png" class="img-btn">Cambio de rol</button>
                    </li>
                    <li>
                        <button id="cambio2" class="limpiador-botones" onclick="cambioPesta2();" ><img src="../assets/icon/users/inactivo.png" class="img-btn">Inactivos</button>
                    </li>

                    <li>
                        <button class="limpiador-botones" >
                            <a href="../intranet/gestion_usuario.php" class="enlaces_limpios"><img src="../assets/icon/users/log-out.png" class="img-btn">Volver</a>
                        </button>
                    </li>               
                </ul>
            </nav>
    
        </div>
    
    ';
}
function barra_lateral_auditoria(){
    echo 
    '
    <div class="banner " id="mainHeader" role="banner">
    
            <nav role="navigation" class="bg-info text-start">
                <div class="top-header">
                    <div class="navg">
                    <div class="efect"></div>
                    </div>
                </div>
    
                <!-- This part is the navigation generated by Wordpress.  -->
                <ul id="menu-vertical-menu" class="nav"  >
                    <li>
                        <button id="cambio1" class="limpiador-botones" onclick="cambioPesta1();" ><img src="../assets/icon/users/usuario-de-perfil.png" class="img-btn">Usuarios</button>
                    </li>
                    <li>
                        <button id="cambio2" class="limpiador-botones" onclick="cambioPesta2();" ><img src="../assets/icon/users/base-de-datos.png" class="img-btn">Base de Datos</button>
                    </li>

                    <li>
                        <button class="limpiador-botones" >
                            <a href="../intranet/gestion_usuario.php" class="enlaces_limpios"><img src="../assets/icon/users/log-out.png" class="img-btn">Volver</a>
                        </button>
                    </li>               
                </ul>
            </nav>
    
        </div>
    
    ';
}
function barra_lateral_corr(){
    echo 
    '
    <div class="banner " id="mainHeader" role="banner">
    
            <nav role="navigation" class="bg-info text-start">
                <div class="top-header">
                    <div class="navg">
                    <div class="efect"></div>
                    </div>
                </div>
    
                <!-- This part is the navigation generated by Wordpress.  -->
                <ul id="menu-vertical-menu" class="nav"  >
                    <li>
                        <button id="cambio3" class="limpiador-botones" onclick="cambioPesta3();" ><img src="../assets/intranet/grafico.png" class="img-btn">Datos</button>
                    </li>
                    <li>
                        <button id="cambio1" class="limpiador-botones" onclick="cambioPesta1();" ><img src="../assets/intranet/correspondencia/archivo.png" class="img-btn">Correspondencia</button>
                    </li>
                    <li>
                        <button id="cambio2" class="limpiador-botones" onclick="cambioPesta2();" ><img src="../assets/intranet/correspondencia/envio.png" class="img-btn">Registros</button>
                    </li>

                    <li>
                        <button class="limpiador-botones" >
                            <a href="../intranet/correspondencia_menu.php" class="enlaces_limpios"><img src="../assets/icon/users/log-out.png" class="img-btn">Volver</a>
                        </button>
                    </li>               
                </ul>
            </nav>
    
        </div>
    
    ';
}


?>